#include <iostream>
#include <string>
using namespace std;

int main()
{
	cout << "<html>" << endl;
	cout << "<head>" << endl;
	cout << "<title>My C++ website</title>" << endl;
	cout << "</head>" << endl;
	cout << "<body>" << endl;
	cout << "<h1>This website was generated by C++</h1>" << endl;
	cout << "<p>Welcome to my c++ website<p/>" << endl;
	cout << "</body>" << endl;
	cout << "</html>" << endl;
	
	return 0;
}